config/routes.rb
Seedcompany::Application.routes.draw do

  devise_for :customers
  devise_for :admins

  devise_scope :admins do
    get 'admins', :to => 'seeds#index', :as => :admin_root # Rails 3
  end

  scope "/admin" do
    resources :customers
  end

  match 'products/:id' => 'seeds#product', :as => :products
  match 'cart' => 'customers#cart', :as => :cart
  match 'add' => 'customers#add_item', :as => :add_item
  match 'remove' => 'customers#remove_item', :as => :remove_item
  match 'update_item' => 'customers#update_item', :as => :update_item
  match 'empty_cart' => 'customers#empty_cart', :as => :empty_cart

  resources :seeds do
    resources :photos
    resources :packets
  end

  resources :orders do
    resources :order_items
  end

  root :to => 'seeds#shop'

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :orders	
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  attr_accessible :first_name, :last_name, :address_one, :address_two, :city, :state_province
  attr_accessible :country, :postal_code, :business_name, :phone_number

  validates_presence_of :first_name, :last_name, :address_one, :city, :state_province, :country, :postal_code, :phone_number

  accepts_nested_attributes_for :orders
  attr_accessible :orders_attributes

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_filter :authenticate_admin!, :except => [:cart, :add_item, :remove_item, :update_item, :empty_cart]
  layout 'admin_layout', :except => [:cart, :add_item, :remove_item, :update_item, :empty_cart]
  before_filter :authenticate_customer!, :only => [:add_item, :remove_item, :update_item, :empty_cart]

  def add_item
    @customer = current_customer
    @order = Order.where(:customer_id => @customer.id, :order_status => "CART").first
    if @order.nil?
      @order = @customer.orders.build
      @order.order_status = "CART"
      @order.save
    end

    @packet = Packet.find(params[:packet])
    quantity = params[:quantity].to_i

    # If product isn't in cart already, add. Else, ignore.
    @oi = OrderItem.where(:packet_id => @packet.id, :order_id => @order.id).first
    if @oi.nil?
      @oi = @order.order_items.build(:packet_id => @packet.id, :cost => @packet.price, :quantity => quantity)
      @oi.save
    end

    redirect_to "/cart"

  end



  def remove_item
    @orderItem = OrderItem.find(params[:order_item])
    @orderItem.destroy

    redirect_to "/cart"
  end



  def update_item
    @orderItem = OrderItem.find(params[:order_item])
    @orderItem.update_attributes(:quantity => params[:quantity])

    respond_to do |format|
      format.html { redirect_to "/cart", notice: "Cart was updated." }
    end
  end



  def empty_cart
    @order = Order.find(params[:order])
    if @order.destroy
      redirect_to "/cart", notice: "Cart was emptied."
    end
  end


  def cart
    @customer = current_customer
    @order = Order.basic_search(:customer_id => @customer.id).first

    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end


  # GET /customers
  # GET /customers.json
  def index
    if params[:search].present?
      @customers = Customer.order('id DESC').basic_search(params[:search]).page(params[:page])
    else
      @customers = Customer.order('id DESC').page(params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: customers_path }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    if params[:customer][:password].blank?
      params[:customer].delete(:password)
      params[:customer].delete(:password_confirmation)
    end

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
  

end

app/views/customers/cart.html.haml
%h3 Shopping Cart

- if @order
  - if @order.order_items.present?
    %table.cart.table-striped
      %tr
        %th Item
        %th Price
        %th Quantity
        %th

      - @order.order_items.each do |oi|
        %tr
          %td= oi.get_packet_name
          %td= number_with_precision(oi.cost, :precision => 2)
          %td
            = form_for "", :html => { :class => "what" }, :url => { :controller => 'customers', :action => 'update_item'} do |f|
              = f.text_field :quantity, :class => "uq", :name => "quantity", :id => "quantity", :value => oi.quantity
              = f.hidden_field :order_item, :name => "order_item", :id => "order_item", :value => oi.id
          %td= link_to "remove", remove_item_path(:order_item => oi)
  %br
  %div= link_to "Empty Cart", empty_cart_path(:order => @order), :confirm => "Are you sure you want to empty your cart?"
- else
  %p Your cart is currently empty.

app/views/customers/edit.html.haml
%h2
  Edit Customer
= simple_form_for @customer do |f|
  = f.error_notification
  .form-inputs
    = f.input :email, :required => true, :autofocus => true

    = f.input :first_name, :required => true
    = f.input :last_name, :required => true
    = f.input :address_one, :required => true
    = f.input :address_two
    = f.input :city, :required => true
    = f.input :state_province, label: "State/Province", :required => true
    = f.input :country, :required => true
    = f.input :postal_code, :required => true
    = f.input :business_name
    = f.input :phone_number, :required => true
    
    = f.input :password, :autocomplete => "off", :hint => "Leave blank if you don't want to change your password", :required => false
    = f.input :password_confirmation, :required => false
  .form-actions
    = f.button :submit, "Update"

app/views/customers/index.html.haml
- model_class = Customer
.page-header
  %h2 Customer List

- if @customers.present?
  %table.table.table-striped
    %thead
      %tr
        %th ID
        %th Name
        %th Email
        %th Phone #
        %th Location
    %tbody
      - @customers.each do |c|
        %tr
          %td= link_to c._id, edit_customer_path(c)
          %td= "#{c.last_name}, #{c.first_name}"
          %td= c.email
          %td= c.phone_number
          %td= "#{c.city}, #{c.state_province} (#{c.country})"
  %p= paginate(@customers)

= link_to "Add New Customer", new_customer_path

app/views/customers/new.html.haml
%h2 Add New Customer
= simple_form_for @customer do |f|
  = f.error_notification
  .form-inputs
    = f.input :email, :required => true, :autofocus => true
    = f.input :password, :required => true
    = f.input :password_confirmation, :required => true
    = f.input :first_name, :required => true
    = f.input :last_name, :required => true
    = f.input :address_one, :required => true
    = f.input :address_two
    = f.input :city, :required => true
    = f.input :state_province, label: "State/Province", :required => true
    = f.input :country, :required => true
    = f.input :postal_code, :required => true
    = f.input :business_name
    = f.input :phone_number, :required => true

  .form-actions
    = f.button :submit, "Add Customer"