config/routes.rb
Seedcompany::Application.routes.draw do

  devise_for :customers
  devise_for :admins

  devise_scope :admins do
    get 'admins', :to => 'seeds#index', :as => :admin_root # Rails 3
  end

  scope "/admin" do
    resources :customers
  end

  match 'products/:id' => 'seeds#product', :as => :products
  match 'cart' => 'customers#cart', :as => :cart
  match 'add' => 'customers#add_item', :as => :add_item
  match 'remove' => 'customers#remove_item', :as => :remove_item
  match 'update_item' => 'customers#update_item', :as => :update_item
  match 'empty_cart' => 'customers#empty_cart', :as => :empty_cart

  resources :seeds do
    resources :photos
    resources :packets
  end

  resources :orders do
    resources :order_items
  end

  root :to => 'seeds#shop'

  

end

app/models/seed.rb
class Seed < ActiveRecord::Base
  has_many :packets
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :packets, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :photos, :reject_if => :all_blank, :allow_destroy => true
  
  attr_accessible :catalog_number, :common_name, :date_acquired, :days_to_maturity, :genus
  attr_accessible :germination, :notes, :organic, :origin, :seed_type, :species, :sub_species, :variety
  attr_accessible :featured, :categories, :pinyin
  attr_accessible :packets_attributes
  attr_accessible :photos_attributes

  validates_presence_of :catalog_number, :common_name, :variety
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController

  before_filter :authenticate_admin!, :except => [:shop, :product]
  layout 'admin_layout', :except => [:shop, :product]
  respond_to :html, :xml

    # Front page
  def shop
    if params[:search].present?
      @seeds = Seed.order(:common_name, :variety).basic_search(params[:search]).page(params[:page])
    elsif params[:cats].present?
      @seeds = Seed.order(:common_name, :variety).basic_search(categories: params[:cats]).page(params[:page])
    else
      @seeds = Seed.basic_search(featured: true).page(params[:page])
    end

    respond_with @seeds
  end

  # Seed description
  def product
    @seed = Seed.find(params[:id])
    respond_with @seed
  end

  # GET /seeds
  # GET /seeds.json
  def index
    if params[:search].present?
      @seeds = Seed.order(:catalog_number).basic_search(params[:search]).page(params[:page])
    else
      @seeds = Seed.order(:catalog_number).page params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seeds }
    end
  end

  # GET /seeds/1
  # GET /seeds/1.json
  def show
    @seed = Seed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/new
  # GET /seeds/new.json
  def new
    @seed = Seed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seed }
    end
  end

  # GET /seeds/1/edit
  def edit
    @seed = Seed.find(params[:id])
  end

  # POST /seeds
  # POST /seeds.json
  def create
    @seed = Seed.new(params[:seed])

    respond_to do |format|
      if @seed.save
        format.html { redirect_to @seed, notice: 'Seed was successfully created.' }
        format.json { render json: @seed, status: :created, location: @seed }
      else
        format.html { render action: "new" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seeds/1
  # PUT /seeds/1.json
  def update
    @seed = Seed.find(params[:id])

    respond_to do |format|
      if @seed.update_attributes(params[:seed])
        format.html { redirect_to edit_seed_path, notice: 'Seed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seeds/1
  # DELETE /seeds/1.json
  def destroy
    @seed = Seed.find(params[:id])
    @seed.destroy

    respond_to do |format|
      format.html { redirect_to seeds_url }
      format.json { head :no_content }
    end
  end

  def customer_list

    if params[:search].present?
      @customers = Customer.order(:id).basic_search(params[:search])
    else
      @customers = Customer.order(:id).all
    end

    respond_to do |format|
      format.html
      format.json { render json: @customers }
    end

  end

end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/views/seeds/_form.html.haml
= simple_form_for @seed, :html => { :class => 'form-horizontal' } do |f|
    
  = f.input :catalog_number  
  = f.input :common_name  
  = f.input :variety   
  = f.input :genus    
  = f.input :species 
  = f.input :sub_species
  = f.input :pinyin
  = f.input :organic
  = f.input :seed_type
  = f.input :origin
  = f.input :date_acquired, as: :date
  = f.input :germination, :input_html => { :size => 3 }
  = f.input :days_to_maturity, :input_html => { :size => 3, :maxlength => 3 }
  = f.input :featured, label: "Featured?"
  = f.input :notes, as: :text, :input_html => { :size => "100x10" }
  #cats.nested-fields
    %h3 Categories
    = f.collection_check_boxes :categories, %w[cover\ crop flower fruit grain herb vegetable], :to_s, :to_s
  #packets
    = f.simple_fields_for :packets, :html => { :class => 'form-horizontal' } do |packet|
      = render 'packet_fields', :f => packet
    .links
      = link_to_add_association '> Add New Packet Size', f, :packets

  #photos
    = f.simple_fields_for :photos, :html => { :multipart => true, :class => 'form-horizontal' } do |photo|
      = render 'photo_fields', :f => photo
    .links
      = link_to_add_association '> Add New Photo', f, :photos
  
  .form-actions
    = f.submit nil

app/views/seeds/_packet_fields.html.haml
.nested-fields
  %h3 Packet
  = f.input :packet_size
  = f.input :price, :input_html => { :size => 6 }
  = f.input :quantity_available, :input_html => { :size => 10 }
  = f.input :discount_percentage, :input_html => { :size => 3 }
  = link_to_remove_association "> Remove Packet Size", f

app/views/seeds/_photo_fields.html.haml
.nested-fields
  %h3 Photo
  - if f.object.new_record?
    %p
      = f.file_field :photo_url
    %p= link_to_remove_association "> Cancel", f
  - else
    %table
      %tr
        %td= link_to image_tag(f.object.photo_url.url(:thumb)), f.object.photo_url.url
        %td
          = f.check_box :_destroy
          = f.label :_destroy, "Destroy?", :style => "display: inline"

app/views/seeds/customer_list.html.haml
- model_class = Customer
.page-header
  %h2 Customer List

- if !@customers.nil?
  %table.table.table-striped
    %thead
      %tr
        %th ID
        %th Name
        %th Email
        %th Phone #
        %th Location
    %tbody
      - @customers.each do |c|
        %tr
          %td= c._id
          %td= "#{c.last_name}, #{c.first_name}"
          %td= c.email
          %td= c.phone_number
          %td= "#{c.city}, #{c.state_province} (#{c.country})"

= link_to "Add New Customer", new_customer_registration_path

app/views/seeds/edit.html.haml
- model_class = Seed
.page-header
  %h3=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/seeds/index.html.haml
- model_class = Seed
.page-header
  %h2 Seeds List

- if @seeds.present?  
  %table.table.table-striped
    %thead
      %tr
        %th Catalog #
        %th Common Name
        %th Variety
        %th Genus
        %th Species
        %th Sub-Species
        %th Categories
    %tbody
      - @seeds.each do |seed|
        %tr
          %td= link_to seed.catalog_number, edit_seed_path(seed)
          %td= seed.common_name
          %td= seed.variety
          %td= seed.genus
          %td= seed.species
          %td= seed.sub_species
          %td
            - seed.categories.each do |cat|
              %p= cat

  %p= paginate @seeds

= link_to "Add New Seed Variety", new_seed_path

app/views/seeds/new.html.haml
- model_class = Seed
.page-header
  %h2 Add Seed to Catalog
= render :partial => "form"

app/views/seeds/product.html.haml
- model_class = Seed

%h3= "#{@seed.common_name}, #{@seed.variety}"

- if @seed.photos.present?
  .pull-left
    - @seed.photos.each do |p|
      %p.thumbs= image_tag(p.photo_url.url(:thumb))

  .pull-left.well.full-photo
    = image_tag(@seed.photos.first.photo_url.url)

.single-product-description.pull-left
  %p
    %b Catalog Number:
    = @seed.catalog_number

  %p
    %b Botanical Name:
    = "#{@seed.genus} #{@seed.species}"
    - if @seed.sub_species?
      = "var. #{@seed.sub_species}"

  - if @seed.pinyin
    %p
      %b Pinyin:
      = @seed.pinyin

  - if @seed.organic?
    %p
      %b Organic:
      %i.icon-ok

  - if @seed.seed_type?
    %p
      %b Seed Type:
      = @seed.seed_type

  - if @seed.days_to_maturity?
    %p
      %b Days to maturity:
      = @seed.days_to_maturity

  - if @seed.germination?
    %p
      %b Germ:
      = "#{@seed.germination}%"

  - if @seed.notes?
    %p
      %b Notes:
      = @seed.notes


  - if !@seed.packets.nil?
    %table.packets-list
      %tr
        %th Size
        %th Quantity
        %th
      - @seed.packets.each do |packet|
        %tr
          = form_for "", :url => { :action => 'add_item', :controller => 'customers' } do |f|
            %td= packet.packet_size         
            %td
              = f.text_field :quantity, :name => :quantity, :maxlength => 3, :value => 1, :class => "tinytiny"
              = f.hidden_field :packet, :name => :packet, :value => packet.id
            %td= f.submit "Add"
  

app/views/seeds/shop.html.haml
- if !params[:search].present? && !params[:cats].present?
  .hero-unit
    %h1 Seeds Company
    %p broadcasting live
- else
  - if params[:cats].present?
    %h3= params[:cats].titleize
  - elsif params[:search].present?
    %h3
      = "results for: "
      %i= params[:search]
  %p
    = @seeds.length
    = @seeds.length == 1 ? 'result' : 'results'

- if @seeds.present?
  .product-block
    %table.table
      %tbody
        - @seeds.each do |seed|
          %tr
            - if seed.photos.present?
              %td.seed-image= link_to image_tag(seed.photos.first.photo_url.url(:thumb)), products_url(:id => seed.id)
            -else
              %td.seed-image= link_to image_tag("default.png"), products_url(:id => seed.id)
            %td.seed-description
              %p.seed-title= link_to "#{seed.common_name}, #{seed.variety}", products_url(:id => seed.id)
              %p
                %i= seed.pinyin
              %p
                = seed.seed_type
                = seed.organic ? "OG" : nil
              / If the description is too long, cut its length
              %p= seed.notes.length > 250 ? truncate(seed.notes, :length => 250 ) : seed.notes
  %p= paginate @seeds

app/views/seeds/show.html.haml
- model_class = Seed
.page-header
  %h3= "#{@seed.catalog_number}: #{@seed.variety} #{@seed.common_name}"

%p
  %b Name
  = "#{@seed.genus} #{@seed.species}"
  - if @seed.sub_species?
    = "var. #{@seed.sub_species}"

- if @seed.pinyin
  %p
    %b Pinyin
    = @seed.pinyin 

%p
  %b Organic:
  - if @seed.organic?
    = "Yes"
  - else
    = "No"

- if @seed.seed_type?
  %p
    %b Type:
    = @seed.seed_type

- if @seed.days_to_maturity?
  %p
    %b Days to maturity:
    = @seed.days_to_maturity

- if @seed.germination?
  %p
    %b Germ:
    = "#{@seed.germination}%"

- if @seed.origin?
  %p
    %b Origin:
    = @seed.origin

- if @seed.date_acquired?
  %p
    %b Date Acquired:
    = @seed.date_acquired

- if @seed.notes?
  %p
    %b Notes:
    = @seed.notes


- if !@seed.packets.nil?
  %b Packets Available:
  %ul
    - @seed.packets.each do |packet|
      %li
        %b= packet.packet_size
        = "(#{packet.quantity_available})"
        = " - $#{packet.price}"

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), seeds_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_seed_path(@seed), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), seed_path(@seed), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'