config/routes.rb
Seedcompany::Application.routes.draw do

  devise_for :customers
  devise_for :admins

  devise_scope :admins do
    get 'admins', :to => 'seeds#index', :as => :admin_root # Rails 3
  end

  scope "/admin" do
    resources :customers
  end

  match 'products/:id' => 'seeds#product', :as => :products
  match 'cart' => 'customers#cart', :as => :cart
  match 'add' => 'customers#add_item', :as => :add_item
  match 'remove' => 'customers#remove_item', :as => :remove_item
  match 'update_item' => 'customers#update_item', :as => :update_item
  match 'empty_cart' => 'customers#empty_cart', :as => :empty_cart

  resources :seeds do
    resources :photos
    resources :packets
  end

  resources :orders do
    resources :order_items
  end

  root :to => 'seeds#shop'

  

end

app/views/layouts/admin_layout.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Seeds Company"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar
      .navbar-inner
        %ul.nav.admin-nav
          %li= link_to "Admin", seeds_path
          - if admin_signed_in?
            %li= link_to current_admin.email, edit_admin_registration_path
            %li= link_to "Log Out", destroy_admin_session_path, :method => :delete
          -else
            %li= link_to "Login", new_admin_session_path
            %li= link_to "Register Admin", new_admin_registration_path

    .container
      .row
        .span3.admin
          .well.sidebar-nav
            .nav-header Shop
            %ul.nav.nav-list
              %li= link_to "Front Page", root_path, :target => "_blank"
            .nav-header Customers
            %ul.nav.nav-list
              %li= link_to "Add New Customer", new_customer_path
              %li= link_to "Customer List", customers_path
            .nav-header Seeds
            %ul.nav.nav-list
              %li= link_to "Add New Seed", new_seed_path
              %li= link_to "Seeds List", seeds_path
        .span9
          = bootstrap_flash
          - if current_page?(customers_path)
            = form_tag customers_path, :method => :get do
              %p.pull-right.search
                = text_field_tag :search, params[:search]
                = submit_tag "Search Customers", :class => :btn
          -elsif current_page?(seeds_path)
            = form_tag seeds_path, :method => :get do
              %p.pull-right.search
                = text_field_tag :search, params[:search]
                = submit_tag "Search Seeds", :class => :btn
          = yield
    
      %footer
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Seeds Company"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .container.shop
      .navbar
        .navbar-inner
          %ul.nav
            %li.app-title
              %i.icon-leaf
              = link_to "Seeds Company", root_path
            - if customer_signed_in?
              %li.cart-horse
                = link_to current_customer.email, edit_customer_registration_path
                = link_to "(sign out)", destroy_customer_session_path, :method => :delete
              %li.cart-horse
                %i.icon-shopping-cart= link_to " cart", "/cart"
            -else
              %li.cart-horse= link_to "Sign In", new_customer_session_path
              %li.cart-horse= link_to "Register", new_customer_registration_path


          
          = form_tag root_path, :method => :get do
            %p.navbar-search
              %i.icon-search
              = text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search"

      .row
        .span3
          .well.sidebar-nav
            .nav-header Categories
            %ul.nav.nav-list
              %li= link_to "Cover Crops", root_path(:cats => "cover crops")
              %li= link_to "Flowers", root_path(:cats => "flowers")
              %li= link_to "Fruit", root_path(:cats => "fruits")
              %li= link_to "Grains", root_path(:cats => "grains")
              %li= link_to "Herbs", root_path(:cats => "herbs")
              %li= link_to "Vegetables", root_path(:cats => "vegetables")
            %ul.nav.nav-list
              %li= link_to "Open-Pollinated", root_path(:search => "open-pollinated")
        .span9
          = bootstrap_flash
          = yield
      

      %footer
        .navbar
          .navbar-inner
            %ul.pull-right
              %li
                %i.icon-twitter
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"